- name: Install Prerequisites
  apt: name='aptitude' update_cache=yes state=latest force_apt_get=yes

- name: Install LEMP Packages
  apt: 
    name: "{{ item }}"
    update_cache: yes 
    state: latest
  with_items: 
    - mysql-server
    - python3-pip
    - libmysqlclient-dev
    - python3-dev
    - python3-mysqldb
    - python3-pymysql
    - php
    - php-common
    - php-cli
    - php-dev
    - php-fpm
    - php-mysql
    - php-mbstring 
    - php-gd

- name: "UFW - Allow HTTP on port {{ http_port }}"
  ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp