---
- name: Install the PHP7 Repository
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present

- name: Install PHP7-FPM
  apt:
    name: "{{ ubuntu_php_pkgs }}"
    state: latest
    update_cache: yes

- name: Copy the templates to their respestive destination
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
  with_items:
    - { src: 'www.conf.j2', dest: '/etc/php/7.0/fpm/pool.d/www.conf' }
  notify:
    - Restart PHP7-FPM 